# Generated by Django 3.2.4 on 2021-06-17 15:18

from django.db import migrations
import esp.models


class Migration(migrations.Migration):

    dependencies = [
        ('esp', '0002_auto_20210617_1944'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', esp.models.UserManager()),
            ],
        ),
    ]
