# Generated by Django 3.2.4 on 2022-01-02 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esp', '0004_auto_20210617_2005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterField(
            model_name='user',
            name='expression',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='expression'),
        ),
        migrations.AlterField(
            model_name='user',
            name='solution',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='solution'),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set(),
        ),
    ]
