# Generated by Django 3.2.4 on 2022-01-02 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esp', '0005_auto_20220102_0504'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='user',
        #     name='email',
        # ),
        # migrations.RemoveField(
        #     model_name='user',
        #     name='username',
        # ),
        migrations.AlterField(
            model_name='user',
            name='expression',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='expression'),
        ),
        migrations.AlterField(
            model_name='user',
            name='solution',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='solution'),
        ),
    ]
